#!/bin/bash

export Rootfs="$HOME/Box4Droid/ubuntu/"

string='export VK_ICD_FILENAMES="/opt/turnip-zink/arm64/share/vulkan/icd.d/freedreno_icd.aarch64.json:/opt/turnip-zink/armhf/share/vulkan/icd.d/freedreno_icd.armv8.2l.json"'

if [ "$1" = "--help" ]; then
echo ""
echo " Box4Droid is a simple script that aims to make the usability of Box86/Box64 easier using a pre-configured RootFS with some configuration scripts to help with the use of variables."
echo ""
echo " Here are some parameters to use: "
echo ""
echo "  --help              Show a help page."
echo "  --update            Update the scripts to the latest available version"
echo "  Uninstall-box       It will completely remove all Box4Droid related data (RootFS and Box4Droid folder)"
exit 0
elif [ "$1" = "--update" ]; then
if [ "$(sed '106q;d' $Rootfs/root/.bashrc)" = "export Lang=eng" ]; then
echo "Updating scripts..."
cd $Rootfs/opt/
wget https://github.com/Herick75/Box4Droid/raw/main/Scripts/0.0.3/scripts-En.tar.gz
tar -xvf scripts-En.tar.gz
rm -rf scripts-En.tar.gz
echo " Updated !"
elif [ "$(sed '106q;d' $Rootfs/root/.bashrc)" = "export Lang=ptbr" ]; then
echo "Atualizando..."
cd $Rootfs/opt/
wget https://github.com/Herick75/Box4Droid/raw/main/Scripts/0.0.3/scripts-Ptbr.tar.gz
tar -xvf scripts-Ptbr.tar.gz
rm -rf scripts-Ptbr.tar.gz
echo " Atualizado !"
exit 0
fi
fi

while true; do
clear
echo ""
echo " Please select a resolution for Xvfb :"
echo ""
echo ""
echo "1)640x480 (4:3)"
echo "2)800x600 (4:3)"
echo "3)1024x768 (4:3)"
echo "4)1280x720 (16:9)"
echo "5)1920x1080 (16:9)"
echo "6)1400x600 (7:3)"
echo "0)Exit"


echo ""
echo ""
echo " The 1400x600 resolution manages to adapt to the proportion of the cell phone screen, to use it correctly enter the Termux-x11 settings, and in 'Display resolution mode' set it to 'scaled' and set it to 160%."
echo ""
    read -p " ..." option

    case $option in
        [1]* ) export res=640x480x24;sed -i "109s|.*|export res=640x480|" $Rootfs/root/.bashrc;break;;
        [2]* ) export res=800x600x24;sed -i "109s|.*|export res=800x600|" $Rootfs/root/.bashrc;break;;
	[3]* ) export res=1024x768x24;sed -i "109s|.*|export res=1024x768|" $Rootfs/root/.bashrc;break;;
	[4]* ) export res=1280x720x24;sed -i "109s|.*|export res=1280x720|" $Rootfs/root/.bashrc;break;;
	[5]* ) export res=1920x1080x24;sed -i "109s|.*|export res=1920x1080|" $Rootfs/root/.bashrc;break;;
	[6]* ) export res=1400x600x24;sed -i "109s|.*|export res=1400x600|" $Rootfs/root/.bashrc;break;;
	[0]* ) exit 0;break;;
    esac
done
DISPLAY=:1 termux-x11 &>/dev/null & env DISPLAY=:1 Xvfb -listen tcp :1 -ac -screen 0 $res &>/dev/null & pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &>/dev/null


if [ "$(sed '108q;d' $HOME/Box4Droid/ubuntu/root/.bashrc)" = "export SCRIPT=proot" ]; then

cd $HOME/Box4Droid/

if [ "$(sed '100q;d' $HOME/Box4Droid/ubuntu/root/.bashrc)" = "export GALLIUM_DRIVER=virpipe" ]; then

MESA_NO_ERROR=1 MESA_GL_VERSION_OVERRIDE=4.3COMPAT MESA_GLES_VERSION_OVERRIDE=3.2 virgl_test_server_android &

fi

./start-ubuntu.sh

pkill Xvfb

if [ "$(sed '100q;d' $HOME/Box4Droid/ubuntu/root/.bashrc)" = "export GALLIUM_DRIVER=virpipe" ]; then

pkill virgl_test_serv

fi

pkill -f "app_process / com.termux.x11"

elif [ "$(sed '108q;d' $HOME/Box4Droid/ubuntu/root/.bashrc)" = "export SCRIPT=chroot" ]; then

if [ "$(sudo id -u)" == "0" ]; then

echo ""

echo -e " \033[0;92mRoot access detected successfully !! \033[0m"

echo ""

cd $HOME/Box4Droid

sudo ./chroot.sh

else

sed -i '101s/.*/export LIBGL_DRIVERS_PATH="\/opt\/turnip-zink\/arm64\/lib\/aarch64-linux-gnu\/dri\/:\/opt\/turnip-zink\/armhf\/lib\/arm-linux-gnueabihf\/dri\/:$LIBGL_DRIVERS_PATH"/' $Rootfs/root/.bashrc;

sed -i "102c\\${string}" $Rootfs/root/.bashrc;

sed -i "108s/.*/export SCRIPT=proot/" $Rootfs/root/.bashrc;

echo ""

echo -e " \033[0;91mRoot access not found, going back to Proot mode...\033[0m" & sleep 4

echo ""

cd $HOME/Box4Droid

./start-ubuntu.sh

fi

pkill -f "app_process / com.termux.x11"

pkill Xvfb

elif [ "$(sed '108q;d' $HOME/Box4Droid/ubuntu/root/.bashrc)" = "export SCRIPT=prootdistro" ]; then

if [ "$(sed '100q;d' $HOME/Box4Droid/ubuntu/root/.bashrc)" = "export GALLIUM_DRIVER=virpipe" ]; then

MESA_NO_ERROR=1 MESA_GL_VERSION_OVERRIDE=4.3COMPAT MESA_GLES_VERSION_OVERRIDE=3.2 virgl_test_server_android &

proot-distro login ubuntu --isolated --bind /sdcard:/sdcard --bind $PREFIX/tmp/.virgl_test:/tmp/.virgl_test --bind $PREFIX/tmp/.X11-unix:/tmp/.X11-unix --bind $PREFIX/tmp/.wine-0:/tmp/.wine-0 --no-sysvipc

else

proot-distro login ubuntu --isolated --bind /sdcard:/sdcard --shared-tmp

fi


if [ "$(sed '100q;d' $HOME/Box4Droid/ubuntu/root/.bashrc)" = "export GALLIUM_DRIVER=virpipe" ]; then

pkill virgl_test_serv

pkill -f "app_process / com.termux.x11"

pkill Xvfb

fi

fi

pkill virgl_test_serv

pkill -f "app_process / com.termux.x11"

pkill Xvfb
