#!/bin/bash

while true; do
clear

echo " Por favor, selecione uma linguagem :"
echo ""
echo " Please select a language :"
echo ""
echo ""
echo " 1)Português-BR"
echo ""
echo " 2)English"
echo ""

read -p " ..." option

    case $option in
        [1]* ) curl -o ptbr https://raw.githubusercontent.com/Herick75/Box4Droid/main/Scripts/Lang/ptbr && chmod +x ptbr && . ptbr;break;;
        [2]* ) curl -o eng https://raw.githubusercontent.com/Herick75/Box4Droid/main/Scripts/Lang/eng && chmod +x eng && . eng;break;;
    esac
done
