#!/bin/bash

while true; do
clear

echo " Por favor, selecione uma linguagem :"
echo ""
echo " Please select a language :"
echo ""
echo ""
echo " 1)Português-BR"
echo ""
echo " 2)English"
echo ""

read -p " ..." option

    case $option in
        [1]* ) . ptbr;break;;
        [2]* ) . eng;break;;
    esac
done
